#!/bin/bash
# Author: Amit
# Date Created: 02-Feb-2020
# Date Modified: 24-Feb-2020
# Purpose: Testing
LOG_FILE="/home/sp/start_v2.log"
tvdetect () {
	tail -n 20 logs/tvAdDetect_out.log | grep 'No audio response' >> /dev/null 
	if [ $? -ne 0 ]
	then
		echo Script is running fine
	else
		echo There is an error in the script. Tracking is affected.
		#tail -n 10 logs/tvAdDetect_out.log
	        tail -n 20 logs/tvAdDetect_out.log | grep 'No audio response'
	fi
}
#
while sleep 5
do
	tvdetect >> $LOG_FILE
done
